--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Clarence2810/AchievementReward
build-by-default: true
branches:
- main
projects:
  AchievementReward:
    path: ""
    icon: "icon.png"
...
